### ISSUE TITLE
The binary of "npm" must be installed

### ISSUE THREAD

**Issue by schmunk42** [foxypkg/foxy#2]
Playing around with the foxy....

    The binary of "npm" must be installed

- could it also be `yarn`?
- do I really need to install it, could there be a `--ignore-node-packages` option, just to move on (like a dry-run)?
- would be nice to have links to the installation pages

**Comment by francoispluchino** [comment]
1. Yes
2. `dry-run` compatibility is currently under development but you can pass options for the asset manager, see the [configuration doc](https://github.com/foxypkg/foxy/blob/master/Resources/doc/config.md)
3. For all your questions: see the [get starting doc](https://github.com/foxypkg/foxy/blob/master/Resources/doc/index.md)

**Comment by francoispluchino** [comment]
Can this issue be closed?
