### ISSUE TITLE
Show realtime output of the npm command

### ISSUE THREAD

**Issue by schmunk42** [foxypkg/foxy#4]
I tried running an installation with `-vvv` and expected to see a "real-time" output of the npm command. Is this possible with PHP?

**Comment by francoispluchino** [comment]
Regarding the output, there are 2 things that are less friendly:
- dynamic output not available (Only each new line)
- the colored display which is deactivated

It's Nodejs that disable the dynamic output and the colored output. I did not find an option to force him. I initially thought to disable the output for the asset manager, and it's still better to have this output, in addition, you can add options to NPM / Yarn to do this.
